name: "Build and release"

on:
  push:
    tags:
      - "v*"

jobs:
  build_on_macos:
    runs-on: macos-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install modules
        run: npm ci

      - name: Import apple codesign cert
        uses: apple-actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}

      - name: Build
        run: npm run build:mac:x64
        env:
          ENABLE_NOTARIZE: enable
          APPLEID: ${{ secrets.APPLEID }}
          APPLEIDPASS: ${{ secrets.APPLEIDPASS }}
          TEAMID: ${{ secrets.TEAMID }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: macos-build-artifacts
          path: dist/

  build_on_windows:
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install modules
        run: npm ci

      - name: Build
        run: npm run build:win:x64

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-build-artifact
          path: dist/

  release:
    needs: [build_on_macos, build_on_windows]

    runs-on: ubuntu-latest

    steps:
      - name: Download macos artifacts
        uses: actions/download-artifact@v3
        id: download_mac
        with:
          name: macos-build-artifacts
          path: macos/

      - name: Rename macos Release Asset
        run: |
          mv "${{ steps.download_mac.outputs.download-path }}/Proxy Doggo Handler.dmg" ProxyDoggoHandler-macos.dmg

      - name: Download windows artifacts
        uses: actions/download-artifact@v3
        id: download_win
        with:
          name: windows-build-artifact
          path: windows/

      - name: Rename windows Release Asset
        run: |
          mv "${{ steps.download_win.outputs.download-path }}/Proxy Doggo Handler.exe" ProxyDoggoHandler-win-portable.exe

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            ProxyDoggoHandler-macos.dmg
            ProxyDoggoHandler-win-portable.exe
