name: "Build and release"

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: macos-latest
            build_script: build:mac
          - os: windows-latest
            build_script: build:win64

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Use Node.js v16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm

      - name: Install modules
        run: npm ci

      - name: Import apple codesign cert
        uses: apple-actions/import-codesign-certs@v1
        if: matrix.os == 'macos-latest'
        with:
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}

      - name: Store app-specific password in keychain
        if: matrix.os == 'macos-latest'
        env:
          APPLEID: ${{ secrets.APPLEID }}
          APPLEIDPASS: ${{ secrets.APPLEIDPASS }}
        run: |
          xcrun altool --store-password-in-keychain-item "AC_PASSWORD" -u $APPLEID -p $APPLEIDPASS

      - name: Build
        env:
          APPLEID: ${{ secrets.APPLEID }}
          APPLEIDPASS: ${{ secrets.APPLEIDPASS }}
          ASC_PROVIDER: ${{ secrets.ASC_PROVIDER }}
        run: npm run ${{ matrix.build_script }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: dist/

  release:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true

      - name: Download macos artifacts
        uses: actions/download-artifact@v2
        id: download_mac
        with:
          name: macos-latest
          path: macos/

      - name: Upload macos Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.download_mac.outputs.download-path }}/Proxy Doggo Handler.dmg
          asset_name: ProxyDoggoHandler-macos.dmg
          asset_content_type: application/x-apple-diskimage

      - name: Download windows artifacts
        uses: actions/download-artifact@v2
        id: download_win
        with:
          name: windows-latest
          path: windows/

      - name: Upload windows Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.download_win.outputs.download-path }}/Proxy Doggo Handler.exe
          asset_name: ProxyDoggoHandler-win-portable.exe
          asset_content_type: application/octet-stream
